// <auto-generated />
using BBQ.Services.ProductAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BBQ.Services.ProductAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BBQ.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CategoryName")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = "Appetizer",
                            Description = "Your choice of 100% Angus beef or chicken sliders with homemade barbeque sauce on a Hawaiian sweetbread bun. Choose from Sweet and Tangy, Hot and Spicy, or Honey BBQ sauces with your choice of toppings.",
                            ImageUrl = "https://lisadotnetmastery.blob.core.windows.net/bbq/ImagesForBBQ/sliders2.jpg",
                            Name = "BBQ Sliders",
                            Price = 13.99
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryName = "Appetizer",
                            Description = "What BBQ is complete without a side of Southern Sweet Potato Fries? Hand breaded and fried to perfection. Choose from Tangy Ranch, Dill BBQ sauce, or Honey Mustard to dip them in. Your mouth will thank you!",
                            ImageUrl = "https://lisadotnetmastery.blob.core.windows.net/bbq/ImagesForBBQ/sweetpotatofries2.jpg",
                            Name = "Sweet Potato Fries",
                            Price = 9.9900000000000002
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "Dessert",
                            Description = "A buttery, fall apart in your mouth delicious, flaky crust just like Grandma used to make with sweet and tart apple filling. Enjoy a slice of this multi-generationally handed down family recipe, from our family to ours!",
                            ImageUrl = "https://lisadotnetmastery.blob.core.windows.net/bbq/ImagesForBBQ/applepie2.jpg",
                            Name = "Apple Pie",
                            Price = 10.99
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryName = "Entree",
                            Description = "Cooked to perfection, this beef brisket has been smoking for hours waiting to be enjoyed! <br/>Smoked over a blend of hickory and maple chips for a flavor that cannot be beat!",
                            ImageUrl = "https://lisadotnetmastery.blob.core.windows.net/bbq/ImagesForBBQ/beefbrisket.jpg",
                            Name = "Beef Brisket",
                            Price = 15.99
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
